import shadowReleaseData from "./shadow-release.generated.json";

export type ProductId = "cocoa" | "shadow";

export type Channel = "stable" | "beta" | "alpha" | "lts";

export type Platform = "windows" | "linux" | "macos";

export type Architecture = "x64" | "arm64" | "universal" | "any";

export type FileType =
  | "pypi"
  | "exe"
  | "appimage"
  | "dmg"
  | "zip"
  | "tar.gz";

export interface Artifact {
  platform: Platform;
  arch: Architecture;
  fileType: FileType;
  url: string;
  sizeBytes?: number;
  sha256?: string;
  notesUrl?: string;
  installCommand?: string;
}

export interface Release {
  product: ProductId;
  channel: Channel;
  version: string;
  dateISO: string;
  releasePageUrl: string;
  zipballUrl: string;
  highlights: string[];
  notesMarkdown?: string;
  artifacts: Artifact[];
}

// Shadow is generated by scripts/sync-releases.mjs.
// Cocoa is maintained here from the official Darkelf Cocoa GitHub release.
export const releases: Release[] = [
  shadowReleaseData as Release,

  {
    product: "cocoa",
    channel: "stable",
    version: "7.0.21",
    dateISO: "2026-10-06",

    releasePageUrl:
      "https://github.com/Darkelf-Labs/Darkelf-Cocoa-Browser/releases/tag/v.7.0.21",

    zipballUrl:
      "https://api.github.com/repos/Darkelf-Labs/Darkelf-Cocoa-Browser/zipball/v.7.0.21",

    highlights: [
      "Native macOS privacy browser built with Cocoa, WebKit and PyObjC",
      "Signed and notarized Developer ID DMG for direct macOS installation",
      "Ephemeral browsing with reduced persistent browsing data",
      "Expanded Canvas and WebGL fingerprinting protections",
      "Improved native WebKit content-rule filtering and tracker resistance",
      "Expanded Darkelf Sentinel privacy and tracker detection",
      "Improved browsing-session isolation and WebKit security policies",
      "Dedicated launcher architecture for reliable compiled macOS builds",
      "SHA-256 release verification",
    ],

    notesMarkdown: `
## Darkelf Cocoa 7.0.21

Darkelf Cocoa Browser is a native macOS privacy browser built with
**PyObjC + WebKit**, designed around ephemeral browsing, tracker resistance,
fingerprinting protection, and native macOS integration.

Version **7.0.21** continues the evolution of Darkelf Cocoa with improved
privacy protections, native browser behavior, stability, and a refined
macOS distribution architecture.

## Privacy & Fingerprinting Protection

- Expanded browser fingerprinting protections.
- Improved Canvas readback protection and privacy handling.
- Enhanced WebGL fingerprint resistance.
- Refined screen and timezone spoofing behavior.
- Improved browser identity and environment normalization.
- Expanded protection against common tracking and telemetry techniques.
- Strengthened privacy policy enforcement across browsing sessions.
- Continued use of ephemeral WebKit browsing sessions to minimize
  persistent browsing data.

## Content Blocking & Network Protection

- Major improvements to Darkelf's native WebKit content-rule engine.
- Expanded advertising, tracker, telemetry, and nuisance-domain filtering.
- Improved content-rule generation and compilation.
- Refined network request handling and privacy enforcement.
- Improved cosmetic filtering behavior.
- Better compatibility between privacy protections and normal website
  functionality.
- Improved filter caching and rule-loading reliability.

## Darkelf Sentinel

- Expanded Darkelf Sentinel privacy and tracker detection.
- Improved detection of potentially privacy-invasive browser activity.
- Refined event analysis and reporting.
- Better integration between Sentinel, network protection, and browser
  privacy controls.
- Improved internal privacy telemetry without requiring persistent
  browsing history.

## Security & Isolation

- Improved browsing-session isolation.
- Strengthened security policy handling.
- Refined WebKit navigation and permission policies.
- Improved handling of external and potentially unsafe navigation.
- Additional defensive browser-policy checks.
- Continued privacy-first defaults throughout the browser.

## Native macOS Interface

- Refined native Cocoa user interface.
- Improved tab behavior and management.
- Improved toolbar and address-bar interaction.
- Updated navigation controls and browser icons.
- Updated Darkelf Cocoa branding assets.
- Improved bookmark handling.
- Refined window and page-management behavior.
- Additional interface consistency and usability improvements.

## Downloads & Navigation

- Improved download handling.
- Refined navigation and page lifecycle management.
- Improved handling of links and browser actions.
- Better integration between downloads and native macOS behavior.

## Performance & Stability

- Improved startup behavior.
- More efficient privacy and content-rule initialization.
- Improved WebKit content-rule compilation and caching.
- Reduced unnecessary browser-state processing.
- General performance and memory-management improvements.
- Numerous stability and compatibility fixes.

## macOS Packaging & Distribution

- Updated native macOS application packaging for Darkelf Cocoa 7.0.21.
- Added a dedicated Cocoa application launcher to preserve Python package
  context in compiled builds.
- Improved Nuitka application-bundle generation.
- Improved bundled asset handling for native Darkelf branding.
- Developer ID Application signing with Hardened Runtime.
- Apple notarization and stapling support for direct macOS distribution.
- Signed and notarized DMG distribution workflow.
- Improved Gatekeeper compatibility for downloaded releases.
- Added SHA-256 release verification support.

## Architecture

Darkelf Cocoa uses a modular native macOS architecture built around
Cocoa, WebKit and PyObjC.

Version 7.0.21 uses a dedicated application launcher for compiled macOS
builds, allowing the modular darkelf_cocoa package to retain the correct
package context when distributed as a native application bundle.

## Fixes

- Fixed compiled application startup caused by package-relative import handling.
- Improved native application launcher behavior.
- Improved macOS application packaging reliability.
- Fixed and refined bundled branding asset handling.
- Improved Developer ID signing and notarization workflow.
- Improved runtime validation before DMG creation.
- Fixed various UI and navigation inconsistencies.
- Improved content-rule reliability.
- Improved compatibility with modern websites.
- Refined privacy protections to reduce unnecessary site breakage.
- Improved internal error handling.
- General code cleanup and maintenance.
- Numerous minor stability fixes throughout the browser.

## Technical

- Native PyObjC + WebKit macOS architecture.
- Python 3.11+.
- Modularized Darkelf Cocoa codebase.
- Dedicated launcher architecture for compiled macOS builds.
- Nuitka-based native macOS application packaging.
- Developer ID Application signed.
- Hardened Runtime enabled.
- Apple notarized and stapled application.
- Signed, notarized and stapled DMG distribution.
- SHA-256 release checksum support.

## Release Verification

DMG SHA-256:

\`\`\`text
ece60f9f113f7070daa20d08cd744a3066e81e0dda67aaafe0eadf6ed85ba6b3
\`\`\`
`,

    artifacts: [
      {
        platform: "macos",
        arch: "any",
        fileType: "dmg",

        url:
          "https://github.com/Darkelf-Labs/Darkelf-Cocoa-Browser/releases/download/v.7.0.21/Darkelf-Cocoa-7.0.21.dmg",

        sizeBytes: 24953253,

        sha256:
          "ece60f9f113f7070daa20d08cd744a3066e81e0dda67aaafe0eadf6ed85ba6b3",

        notesUrl:
          "https://github.com/Darkelf-Labs/Darkelf-Cocoa-Browser/releases/tag/v.7.0.21",
      },
    ],
  },
];
