import shadowReleaseData from "./shadow-release.generated.json";

export type ProductId = "cocoa" | "shadow";

export type Channel = "stable" | "beta" | "alpha" | "lts";

export type Platform = "windows" | "linux" | "macos";

export type Architecture = "x64" | "arm64" | "universal" | "any";

export type FileType =
  | "pypi"
  | "exe"
  | "appimage"
  | "dmg"
  | "zip"
  | "tar.gz";

export interface Artifact {
  platform: Platform;
  arch: Architecture;
  fileType: FileType;
  url: string;
  sizeBytes?: number;
  sha256?: string;
  notesUrl?: string;
  installCommand?: string;
}

export interface Release {
  product: ProductId;
  channel: Channel;
  version: string;
  dateISO: string;
  releasePageUrl: string;
  zipballUrl: string;
  highlights: string[];
  notesMarkdown?: string;
  artifacts: Artifact[];
}

// Shadow is generated by scripts/sync-releases.mjs.
// Cocoa retains its existing release information.
export const releases: Release[] = [
  shadowReleaseData as Release,

  {
    product: "cocoa",
    channel: "stable",
    version: "7.0.7",
    dateISO: "2026-07-28",
    releasePageUrl: "",
    zipballUrl: "",

    highlights: [
      "Lightweight native macOS browser built with Cocoa, WebKit and PyObjC",
      "Available through PyPI for pip installation",
      "Ephemeral browsing with no persistent cookies, cache or history",
      "MiniAI Sentinel security monitoring",
      "Canvas fingerprint protection",
      "First-party isolation",
      "Tracker blocking and privacy protections",
    ],

    notesMarkdown: `
## Darkelf Cocoa 7.0.7

Darkelf Cocoa is the lightweight native macOS browser in the Darkelf
Browser ecosystem.

It is built with Cocoa, WebKit and PyObjC and distributed through PyPI.

### Installation

\`\`\`bash
pip install darkelf-cocoa
\`\`\`

## What's New

- Improved MiniAI Sentinel.
- Enhanced tracker blocking.
- Improved session isolation.
- Better toolbar and UI responsiveness.

## Security

- Improved fingerprint protections.
- Hardened ephemeral browsing.
- Updated privacy safeguards.

## Fixes

- Various bug fixes.
- Improved stability.
- Minor UI refinements.
`,

    artifacts: [
      {
        platform: "macos",
        arch: "any",
        fileType: "pypi",
        url: "",
        sizeBytes: 0,
        installCommand: "pip install darkelf-cocoa",
      },
    ],
  },
];
