import shadowReleaseData from "./shadow-release.generated.json";

export type ProductId = "cocoa" | "shadow";

export type Channel = "stable" | "beta" | "alpha" | "lts";

export type Platform = "windows" | "linux" | "macos";

export type Architecture = "x64" | "arm64" | "universal" | "any";

export type FileType =
  | "pypi"
  | "exe"
  | "appimage"
  | "dmg"
  | "zip"
  | "tar.gz";

export interface Artifact {
  platform: Platform;
  arch: Architecture;
  fileType: FileType;
  url: string;
  sizeBytes?: number;
  sha256?: string;
  notesUrl?: string;
  installCommand?: string;
}

export interface Release {
  product: ProductId;
  channel: Channel;
  version: string;
  dateISO: string;
  releasePageUrl: string;
  zipballUrl: string;
  highlights: string[];
  notesMarkdown?: string;
  artifacts: Artifact[];
}

// Shadow is generated by scripts/sync-releases.mjs.
// Cocoa is maintained here from the official Darkelf Cocoa GitHub release.
export const releases: Release[] = [
  shadowReleaseData as Release,

  {
    product: "cocoa",
    channel: "stable",
    version: "7.0.21",
    dateISO: "2026-10-06",

    releasePageUrl:
      "https://github.com/Darkelf-Labs/Darkelf-Cocoa-Browser/releases/tag/v.7.0.21",

    zipballUrl:
      "https://api.github.com/repos/Darkelf-Labs/Darkelf-Cocoa-Browser/zipball/v.7.0.21",

    highlights: [
      "Native macOS privacy browser built with Cocoa, WebKit and PyObjC",
      "Ephemeral browsing with reduced persistent browsing data",
      "Expanded Canvas and WebGL fingerprinting protections",
      "Improved native WebKit content filtering and tracker resistance",
      "Enhanced Darkelf Sentinel privacy monitoring",
      "Improved stability, compatibility and native macOS behavior",
    ],

    notesMarkdown: `## Darkelf Cocoa 7.0.21

Darkelf Cocoa 7.0.21 improves privacy protection, native WebKit filtering,
browser stability, and macOS integration.

### Privacy & Protection

- Expanded Canvas, WebGL, and fingerprinting protections.
- Improved tracker, advertising, telemetry, and nuisance filtering.
- Enhanced Darkelf Sentinel privacy and tracker detection.
- Improved browsing-session isolation and WebKit security policies.
- Continued ephemeral WebKit browsing to reduce persistent browsing data.

### Browser Improvements

- Refined tabs, navigation, downloads, bookmarks, and native UI behavior.
- Improved content-rule compilation and caching.
- Improved compatibility with modern websites.
- General performance, stability, and reliability improvements.

### macOS Distribution

- Native Cocoa / AppKit / WebKit architecture.
- Python 3.11+ with PyObjC.
- Developer ID signed with Hardened Runtime.
- Apple notarized and stapled application and DMG.
`,

    artifacts: [
      {
        platform: "macos",
        arch: "any",
        fileType: "dmg",

        url:
          "https://github.com/Darkelf-Labs/Darkelf-Cocoa-Browser/releases/download/v.7.0.21/Darkelf-Cocoa-7.0.21.dmg",

        sizeBytes: 24953253,


        notesUrl:
          "https://github.com/Darkelf-Labs/Darkelf-Cocoa-Browser/releases/tag/v.7.0.21",
      },
    ],
  },
];

